name: "01 - Using Actions"

on:
  push:
    branches:
      - idonotexist

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.3

        # https://github.com/marketplace/actions/azure-blob-storage-upload
      - name: Azure Blob Upload
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_BLOB_SAS_CONNECTIONSTRING }}
          container_name: winadmins-githubactions
          sync: true
          source_dir: ${{ github.workspace }}