name: "02 - Multiple jobs"

on:
  push:
    branches:
      - idonotexist

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print datetime (job 1)
        run: Get-Date
        shell: pwsh

  job-2:
    runs-on: windows-latest
    steps:
      - name: Print datetime (job 2)
        run: Get-Date
        shell: pwsh