name: "03 - Environment variables"
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

on:
  push:
    branches:
      - idonotexist

jobs:
  job-1: 
    runs-on: ubuntu-latest
    env:
      myjobworkflowvariable: "Job variable"
    steps:
      - name: Define and print variable x (NOT an environment variable)
        run: |
          $x = "Hello world"
          Write-Output $x
        shell: pwsh

      - name: Print variable x again (NOT an environment variable)
        run: Write-Output $x
        shell: pwsh

      - name: Accessing GITHUB_WORKFLOW (default) environment variable in the shell
        run: Write-Output $env:GITHUB_WORKFLOW
        shell: pwsh

      - name: Create new environment variable to use in later steps
        #run: echo "my_own_variable=yellow" >> $GITHUB_ENV
        run: Write-Output "my_own_variable=yellow" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Read my_own_variable
        run: Write-Output $env:my_own_variable
        shell: pwsh

      - name: Create new multi line environment variable 
        run: |
          echo 'DISTRIBUTIONINFO<<XYZ' >> $GITHUB_ENV
          cat /etc/*lease >> $GITHUB_ENV
          echo 'XYZ' >> $GITHUB_ENV

      - name: Read DISTRIBUTIONINFO
        run: Write-Output $env:DISTRIBUTIONINFO
        shell: pwsh