name: "04b - Job again again, working with a job matrix"
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy

on:
  push:
    branches:
      - idonotexist

jobs:
  job-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-latest, macos-latest]
    steps:
      - name: Hello world
        run: echo "Hello world"