name: "06 - Self hosted runner"
# https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/adding-self-hosted-runners

on:
  push:
    branches:
      - idonotexist

jobs:
  job-1:
    runs-on: self-hosted
    steps:
      - name: List contents of C:\
        run: Get-ChildItem -Path "C:\"

      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Copy everything to a shared folder on-prem
        run: Copy-Item -Path .\ -Destination \\sccm\dummy -Recurse -Force 
        shell: powershell